### ISSUE TITLE
Code to create your re-directed reprexes?

### ISSUE THREAD

**Issue by ddsjoberg** [the-mad-statter/stackexchange#1]
Hello! I've seen a few of your posts on SO using the custom reprex where you're re-directing the output to GH instead of imgur.

I've been thinking about this recently, since moving from an academic environment to a more controlled/regulated space. Do you have the code you used to modify the reprex default behavior somewhere public? I'd love to take a look! I've seen the knitr option to set "upload_fun", but haven't seen a working example before (if that is what you're using). Thanks!

**Comment by the-mad-statter** [comment]
Hi @ddsjoberg, I often use **{reprex}** when posting on SO but thought it might be beneficial to also have actual files hosted somewhere. This is especially true when solutions suggest a good approach would be an RMarkdown/Quarto file or multiple files such as when the question is about CSS or JS in the context of {shiny}.

As such, I am piloting this approach as as supplement to **{reprex}**, but my process is still very manual at this point. I usually take these steps:

1. write and post an answer on SO with the help of {reprex}
2. manually port that answer to files in my local repo along with a readme that points to the SO question
3. push to GitHub
4. generate the GitHub tag with the code [here](https://github.com/the-mad-statter/stackexchange/blob/main/stackoverflow/reprex_file_html_footer/reprex_file_html_footer.R)
5. edit my SO post to include the tag

If at some point I become satisfied with this idea/approach, I was planning on an attempt at automation such as you are describing.

**Comment by ddsjoberg** [comment]
Ahh, thanks for the details. Much appreciated! If you do generalize the solution, I'd love to see it.
